on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  commitizen:
    uses: BlindfoldedSurgery/actions-actions/.github/workflows/commitizen.yml@v1
    with:
      publish-major-tag: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
